import Link from 'next/link';
import {products} from '../data/products';
import {collections,belongsToCollection} from '../lib/collections';
import {ProductCard} from '../components/ProductCard';
import {ProductImage} from '../components/ProductImage';
import {HeroSlides} from '../components/HeroSlides';
import {DeliveryDetails} from '../components/DeliveryDetails';
import {womenWorkforceImage} from '../lib/brandAssets';
import {business,callHref,whatsappHref,partnership} from '../lib/contact';
import {mission} from '../lib/content';
const featured=['mp-sharbati-atta','khapli-wheat-atta','lakdi-ghani-mustard-oil','bilona-cow-ghee','unpolished-whole-cumin','honey','salem-turmeric-powder','black-pepper-whole'];
export function HomePage(){return <>
 <section id="home-delivery" className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Jain Desi & Pure · Noida</span><h1>Fresh atta.<br/><em>In two hours.</em></h1><p>Freshly milled atta, cold-pressed oils, bilona ghee and spices. Everyday food, made with care and delivered to your door.</p><DeliveryDetails/><div className="hero-actions"><Link className="btn btn-primary" href="/shop">Explore the catalog →</Link><a className="btn btn-quiet" href={whatsappHref()} target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a></div></div><HeroSlides/></div></section>
 <section className="originals-section"><div className="container"><div className="section-head"><div><span className="eyebrow">More to discover</span><h2>Find your everyday essentials.</h2><p>Discover more from our collections.</p></div><div className="hero-actions"><Link className="text-link" href="/shop">Full catalog →</Link></div></div><div className="unified-collections">{collections.map(c=><Link href={`/shop/${c.id}`} key={c.id}><ProductImage src={products.find(p=>belongsToCollection(p,c.id)).image} alt={c.name}/><span>{c.name} <b>↗</b></span></Link>)}</div></div></section>
 <section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">A few to start with</span><h2>Our Products</h2></div><p>Choose a pack. See the price. Enquire directly.</p></div><div className="products-grid">{featured.map(id=>products.find(p=>p.id===id)).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
 <section className="mission-preview soft"><div className="container"><span className="eyebrow">Bringing health at the forefront</span><h2>For healthier families.<br/><em>For generations to come.</em></h2><p>{mission}</p><Link className="text-link" href="/about">Our purpose →</Link></div></section>
 <section className="women-workforce"><div className="container workforce-grid"><div className="workforce-copy"><span className="eyebrow">Women at the heart of our work</span><h2>Driven By Women</h2><p>Our vision for better everyday food includes respect for the women who contribute their time, skill and care to this work.</p><p>Food traditions are carried forward through people. We want that contribution to be seen and valued.</p><Link className="text-link" href="/stories/women-behind-jain-desi-and-pure">Read our community story →</Link></div><div className="workforce-gallery"><img className="workforce-main" src={womenWorkforceImage} alt="An illustration of women working together in food preparation" loading="lazy"/></div></div></section>
 <section className="story-section"><div className="container story-grid"><div className="story-image"><img src="/images/process-ghani.jpg" alt="Traditional wooden oil press" loading="lazy"/></div><div className="story-copy"><span className="eyebrow">From ingredient to everyday meal</span><h2>The process.<br/>The people.<br/>The care.</h2><p>Discover how grains, seeds and spices become the staples in your kitchen. Visit our main store to see processing for yourself.</p><div className="hero-actions"><Link className="btn btn-primary" href="/about#process">Our process →</Link><Link className="text-link" href="/contact">Visit our main store →</Link></div></div></div></section>
 <section className="partnership-preview"><div className="container"><div><span className="eyebrow">Grow with Jain Desi</span><h2>Bring better food to your community.</h2><p>An opportunity for entrepreneurs. Minimum investment: {partnership.investment}.</p></div><Link className="btn btn-primary" href="/partnership">Explore partnership →</Link></div></section>
 <section className="home-contact"><div className="container"><div><span className="eyebrow">More to discover, close to home</span><h2>Come say hello.</h2><p>{business.address}</p></div><div className="hero-actions"><a className="btn btn-primary" href={whatsappHref()} target="_blank" rel="noopener noreferrer">WhatsApp us ↗</a><a className="btn btn-quiet" href={callHref}>Call the store</a><Link className="text-link" href="/contact">Our three stores →</Link></div></div></section>
 </>;}
