import Link from 'next/link';
import {products,categories} from '../data/products';
import {ProductCard} from '../components/ProductCard';
import {ProductImage} from '../components/ProductImage';
import {womenWorkforceImage} from '../lib/brandAssets';
import {business,callHref,whatsappHref} from '../lib/contact';
const featured=['mp-sharbati-atta','khapli-wheat-atta','lakdi-ghani-mustard-oil','bilona-cow-ghee','unpolished-whole-cumin','honey'];
export function HomePage(){return <>
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Jain Desi & Pure · Noida</span><h1>Your everyday pantry.<br/><em>Made with care.</em></h1><p>Atta, spices, oils, ghee and the staples your kitchen loves. Browse our full collection and speak directly with our store.</p><div className="hero-actions"><Link className="btn btn-primary" href="/shop">Explore the catalog →</Link><a className="btn btn-quiet" href={whatsappHref()} target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a></div><div className="hero-delivery"><span className="material-symbols-outlined" aria-hidden="true">local_shipping</span><span>{business.delivery}</span></div></div><div className="hero-visual"><img src="/images/chakki-banner.jpg" alt="Traditional stone milling and flour" fetchPriority="high"/><div className="floating-note"><span className="material-symbols-outlined" aria-hidden="true">storefront</span><div><b>Your neighbourhood store</b><small>Sector 122, Noida</small></div></div></div></div></section>
 <section className="originals-section"><div className="container originals-grid"><div><span className="eyebrow">Jain Originals</span><h2>From our pantry.<br/>For yours.</h2><p>Discover our own collection of atta, spices and oils.</p><Link className="text-link" href="/originals">Explore all Originals →</Link></div><div className="originals-collections">{categories.filter(c=>c.original).map(c=><Link href={`/shop/${c.id}`} key={c.id}><ProductImage src={products.find(p=>p.category===c.id).image} alt={c.name}/><span>{c.name} <b>↗</b></span></Link>)}</div></div></section>
 <section className="section pantry-browse"><div className="container"><div className="section-head"><div><span className="eyebrow">Find your essentials</span><h2>One pantry. Plenty to discover.</h2></div><Link className="text-link" href="/shop">View all {products.length} products →</Link></div><div className="pantry-collections">{categories.map((c,i)=><Link key={c.id} href={`/shop/${c.id}`}><span className="collection-number">0{i+1}</span><div><h3>{c.name}</h3><p>{products.filter(p=>p.category===c.id).length} products</p></div><span aria-hidden="true">↗</span></Link>)}</div></div></section>
 <section className="section soft"><div className="container"><div className="section-head"><div><span className="eyebrow">A few to start with</span><h2>Meet your kitchen staples</h2></div><p>Choose a pack. See the price. Enquire directly.</p></div><div className="products-grid">{featured.map(id=>products.find(p=>p.id===id)).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
 <section className="women-workforce"><div className="container workforce-grid"><div className="workforce-copy"><span className="eyebrow">Women at the heart of our work</span><h2>Made with care. Led by women.</h2><p>Women form the main workforce behind Jain Desi &amp; Pure. From careful sorting and quality checks to small-batch packing, their skill, patience and everyday leadership shape every product that leaves our workshop.</p><p>For us, traditional food is also about creating dignified, dependable work close to home—where craft is respected and women grow with the business.</p><div className="workforce-points"><span><b>Skilled hands</b>Careful sorting and preparation</span><span><b>Shared growth</b>Work built around community</span></div></div><div className="workforce-gallery"><img className="workforce-main" src={womenWorkforceImage} alt="Women leading sorting and packing in our small-batch workshop" loading="lazy"/><img className="workforce-small" src="/images/rajasthan-farmers.jpg" alt="Women and farming families preparing a spice harvest" loading="lazy"/></div></div></section>
 <section className="story-section"><div className="container story-grid"><div className="story-image"><img src="/images/process-ghani.jpg" alt="Artisan working with a traditional wooden oil press" loading="lazy"/></div><div className="story-copy"><span className="eyebrow">From crop to cupboard</span><h2>The people.<br/>The process.<br/>The care.</h2><p>Discover the craft behind our pantry and the people who bring it to your kitchen.</p><div className="hero-actions"><Link className="btn btn-primary" href="/our-process">Our process →</Link><Link className="text-link" href="/farmers">Meet our people →</Link></div></div></div></section>
 <section className="home-contact"><div className="container"><div><span className="eyebrow">Here to help</span><h2>Let’s fill your pantry.</h2><p>{business.delivery}</p></div><div className="hero-actions"><a className="btn btn-primary" href={whatsappHref()} target="_blank" rel="noopener noreferrer">WhatsApp us ↗</a><a className="btn btn-quiet" href={callHref}>Call the store</a><Link className="text-link" href="/contact">Visit us →</Link></div></div></section>
 </>;}
