import React from 'react';
import { products, categories } from '../data/products';
import { ProductCard } from '../components/ProductCard';
export const HomePage = ({onNavigate,onSelectProduct}) => <div>
 <section className="hero"><div className="container hero-grid">
  <div className="hero-copy"><span className="eyebrow">From trusted Indian farms to your kitchen</span><h1>Food should taste like where it came from.</h1><p>Stone-ground attas, single-origin spices and wood-pressed oils made in small batches—without shortcuts.</p><div className="hero-actions"><button className="btn btn-primary" onClick={()=>onNavigate('category','attas')}>Shop the harvest</button><button className="btn btn-quiet" onClick={()=>onNavigate('process')}>See how we make it <span>→</span></button></div><div className="hero-proof"><span><b>40 years</b> of food craft</span><span><b>Small batch</b> milling</span><span><b>Direct</b> farm sourcing</span></div></div>
  <div className="hero-visual"><img src="/images/chakki-banner.jpg" alt="Traditional stone milling with freshly ground flour"/><div className="floating-note"><span className="material-symbols-outlined">grain</span><div><b>Freshly milled</b><small>Packed close to dispatch</small></div></div></div>
 </div></section>
 <section className="trust-strip"><div className="container">{[['device_thermostat','Low-heat milling'],['water_drop','First-press oils'],['eco','Single-origin crops'],['science','Batch quality checks']].map(x=><div key={x[1]}><span className="material-symbols-outlined">{x[0]}</span><b>{x[1]}</b></div>)}</div></section>
 <section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Shop by pantry</span><h2>Everyday staples, made exceptionally</h2></div><p>Three focused collections. Nothing filler, nothing over-processed.</p></div><div className="category-grid">{categories.map(c=><button className="category-card" key={c.id} onClick={()=>onNavigate('category',c.id)}><img src={c.banner} alt=""/><span className="category-overlay"><small>Explore collection</small><b>{c.name}</b><i>→</i></span></button>)}</div></div></section>
 <section className="section soft"><div className="container"><div className="section-head"><div><span className="eyebrow">Customer favourites</span><h2>Start with these</h2></div><button className="text-link" onClick={()=>onNavigate('category','oils')}>View all products →</button></div><div className="products-grid">{products.filter(p=>['khapli-wheat-atta','salem-turmeric-powder','alsi-oil-flaxseed','lakdi-ghani-mustard-oil'].includes(p.id)).map(p=><ProductCard key={p.id} product={p} onSelectProduct={onSelectProduct}/>)}</div></div></section>
 <section className="story-section"><div className="container story-grid"><div className="story-image"><img src="/images/process-ghani.jpg" alt="Artisan working with a traditional wooden oil press"/></div><div className="story-copy"><span className="eyebrow">Slow is a standard</span><h2>Traditional methods. Modern discipline.</h2><p>We keep the processes that protect flavour—stone milling, sun drying and wooden pressing—then add clean handling and batch checks.</p><ul><li><span>01</span> Source crops for flavour and traceability</li><li><span>02</span> Process slowly at controlled temperatures</li><li><span>03</span> Pack in practical, protective formats</li></ul><button className="btn btn-primary" onClick={()=>onNavigate('process')}>Our process</button></div></div></section>
 <section className="quote-section"><div className="container"><span className="eyebrow">Our point of view</span><blockquote>“Purity is not a slogan. It is a sequence of small decisions made well.”</blockquote><button className="text-link" onClick={()=>onNavigate('farmers')}>Meet the people behind the harvest →</button></div></section>
</div>;
