'use client';
import {useEffect,useRef,useState} from 'react';
import {attaGrains,prepareAttaBlend} from '../lib/customAtta';
import {ProductImage} from './ProductImage';
export function CustomAtta(){
 const [quantities,setQuantities]=useState({}),[blend,setBlend]=useState(null),[error,setError]=useState(''),summaryRef=useRef(null);
 useEffect(()=>{if(blend){summaryRef.current.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});summaryRef.current.focus({preventScroll:true});}},[blend]);
 function update(id,value){setQuantities(previous=>({...previous,[id]:value}));setBlend(null);setError('');}
 function toggle(id,checked){setQuantities(previous=>{const next={...previous};if(checked)next[id]='100';else delete next[id];return next;});setBlend(null);setError('');}
 function done(event){event.preventDefault();const prepared=prepareAttaBlend(quantities);setBlend(prepared);setError(prepared?'':'Select at least one grain and enter a positive whole-number quantity in grams.');}
 return <section id="custom-atta" className="custom-atta"><span className="eyebrow">Your kitchen, your blend</span><h2>Make your own atta.</h2><p>Select your grains and enter the quantity of each in grams. Our team will confirm whether your blend can be prepared, along with its price and preparation time.</p>
 <form onSubmit={done}><fieldset className="blend-options"><legend>Choose grains for your blend</legend>{attaGrains.map(g=>{const selected=Object.hasOwn(quantities,g.id);return <div className={`blend-grain ${selected?'is-selected':''}`} key={g.id}><button type="button" className="blend-add" aria-label={`${selected?'Remove':'Add'} ${g.name}`} aria-pressed={selected} onClick={()=>toggle(g.id,!selected)}><ProductImage src={g.image} alt="" sizes="(max-width:520px) 40vw, 180px"/><span className="blend-grain-name">{g.name}</span><span className="blend-add-icon material-symbols-outlined" aria-hidden="true">{selected?'check':'add'}</span></button>{selected&&<div className="blend-quantity"><label>Quantity (g)<input type="number" min="1" step="1" required aria-label={`${g.name} quantity in grams`} value={quantities[g.id]} onChange={e=>update(g.id,e.target.value)}/></label><div className="blend-steppers"><button type="button" aria-label={`Decrease ${g.name} by 100 grams`} disabled={Number(quantities[g.id])<=100} onClick={()=>update(g.id,String(Math.max(1,Number(quantities[g.id])-100)))}>−</button><button type="button" aria-label={`Increase ${g.name} by 100 grams`} onClick={()=>update(g.id,String(Number(quantities[g.id])+100))}>+</button></div></div>}</div>;})}</fieldset><div className="blend-form-footer"><p role="status">{Object.keys(quantities).length} grains selected · {Object.values(quantities).reduce((sum,value)=>sum+(Number(value)||0),0)} g total</p><button className="btn btn-primary" type="submit">Done — review my blend</button></div>{error&&<p className="blend-error" role="alert">{error}</p>}</form>
 {blend&&<div ref={summaryRef} tabIndex={-1} className="blend-summary" role="status"><h3>Your atta blend</h3><ul>{blend.grains.map(g=><li key={g.id}>{g.name}: <strong>{g.grams} g</strong></li>)}</ul><p><strong>Total: {blend.total} g</strong></p><a className="btn btn-primary" href={blend.href} target="_blank" rel="noopener noreferrer">Enquire on WhatsApp ↗</a><p className="contact-caption">Review your prepared enquiry in WhatsApp and send it to our team.</p></div>}
 </section>;
}
