'use client';
import {useEffect,useRef} from 'react';
import Link from 'next/link';
import {brandLogo} from '../lib/brandAssets';
import {collections} from '../lib/collections';
import {business,callHref,whatsappHref} from '../lib/contact';

export function ExploreMenu({onClose,opener}){
 const ref=useRef(null),closeRef=useRef(null);
 useEffect(()=>{const dialog=ref.current,openerElement=opener?.current,previousOverflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden';closeRef.current.focus();return()=>{dialog.close();document.body.style.overflow=previousOverflow;if(openerElement?.isConnected)openerElement.focus();};},[opener]);
 return <dialog ref={ref} className="explore-menu" aria-labelledby="explore-title" onCancel={onClose} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();onClose();}}}><div className="explore-inner"><div className="explore-top"><Link href="/" onClick={onClose} aria-label="Jain Desi & Pure home"><img src={brandLogo} alt="Jain Desi & Pure"/></Link><button ref={closeRef} className="explore-close" onClick={onClose} aria-label="Close menu"><span className="material-symbols-outlined" aria-hidden="true">close</span></button></div><h2 id="explore-title">Explore Jain Desi & Pure</h2><div className="explore-layout"><section aria-labelledby="explore-collections"><h3 id="explore-collections">Shop our collections</h3><div className="explore-categories">{collections.map(c=><Link href={`/shop/${c.id}`} key={c.id} onClick={onClose}><img src={`/images/menu-cutouts/${c.id}.png`} alt={c.name} width="64" height="54"/><span>{c.name}<b aria-hidden="true">↗</b></span></Link>)}</div></section><div className="explore-links"><section><h3>Quick pages</h3>{[['Home','/'],['Our Products','/shop'],['Customize Atta','/customize-atta'],['Partnership','/partnership'],['Our mission','/#mission'],['Locations','/#stores'],['Contact','/contact']].map(([label,href])=><Link key={href} href={href} onClick={onClose}>{label}</Link>)}</section><section><h3>Discover</h3><Link href="/#process" onClick={onClose}>Our process</Link><Link href="/#stores" onClick={onClose}>Our stores</Link><Link href="/stories/women-behind-jain-desi-and-pure" onClick={onClose}>Community stories</Link><p>For healthier families.<br/>For generations to come.</p></section><section className="explore-contact"><h3>Talk to our team</h3><a className="btn btn-primary" href={whatsappHref()} target="_blank" rel="noopener noreferrer" onClick={onClose}>Enquire on WhatsApp ↗</a><a className="btn btn-outline" href={callHref} onClick={onClose}>Call {business.displayPhone}</a><p>{business.address}</p></section></div></div></div></dialog>;
}
