import Link from 'next/link';
import {business,callHref,whatsappHref} from '../lib/contact';
import {mission,vision} from '../lib/content';
import {womenWorkforceImage} from '../lib/brandAssets';

export function HomeProcess(){return <section id="process" className="home-process home-section"><div className="container">
 <div className="home-section-heading"><div><span className="eyebrow">The Jain Desi way</span><h2>We sell purity,<br/><em>not packaging.</em></h2></div><p>Good ingredients, traditional wisdom and thoughtful preparation. See what goes into the food you bring home.</p></div>
 <div className="home-process-grid"><div className="process-photo-collage"><figure className="process-photo-main"><img src="/images/process-ghani.jpg" alt="Traditional wooden oil press" loading="lazy"/><figcaption>Traditional pressing</figcaption></figure><figure className="process-photo-small"><img src="/images/chakki-banner.jpg" alt="Stone milling and freshly prepared flour" loading="lazy"/><figcaption>Fresh milling</figcaption></figure></div><div className="process-invitation"><span className="eyebrow">You are welcome at our store</span><h3>Come and see<br/>live processing.</h3><p>Visit our Sector 122 store to see how grains, seeds and spices are prepared. Ask questions. Get to know your everyday food.</p><address>{business.address}</address><div className="home-hero-actions"><Link className="btn btn-primary" href="#stores">Find our store →</Link><a className="text-link" href={callHref}>Call {business.displayPhone} ↗</a></div></div></div>
 <ol className="home-process-steps">{[['Start with good ingredients','Grains, seeds and spices form the foundation.'],['Prepare with care','Thoughtful preparation before milling or pressing.'],['Mill or press','Traditional methods for everyday staples.'],['Pack for your kitchen','Choose a pack and enquire with our team.']].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol>
 </div></section>;}

export function HomeMission(){return <section id="mission" className="home-mission home-section"><div className="container home-mission-grid">
 <div className="home-mission-copy"><span className="eyebrow">Our purpose</span><h2>Putting their health first.<br/><em>Today and for generations to come.</em></h2><p className="mission-statement">Jain Desi &amp; Pure — Bringing health at the forefront.</p><p className="mission-tagline"><em>For healthier families. For generations to come.</em></p><p>{mission}</p><a className="text-link" href={whatsappHref()} target="_blank" rel="noopener noreferrer">Talk to us about your everyday food ↗</a></div>
 <div className="home-vision"><div className="vision-images"><img src="/images/unbranded/khapli-wheat-atta.png" alt="Wheat grains and flour" loading="lazy"/><img src="/images/unbranded/lakdi-ghani-mustard-oil.png" alt="Mustard seeds and cold-pressed oil" loading="lazy"/></div><div className="vision-copy"><span className="eyebrow">Our vision</span><h3>{vision[0]}</h3>{vision.slice(1).map(p=><p key={p}>{p}</p>)}</div></div>
 </div></section>;}

export function HomeWomen(){return <section id="women" className="home-women home-section"><div className="container home-women-grid"><div className="home-women-image"><img src={womenWorkforceImage} alt="An illustration of women working together in food preparation" loading="lazy"/></div><div className="home-women-copy"><span className="eyebrow">Women at the heart of our work</span><h2>Driven By Women.<br/><em>Rooted in care.</em></h2><p>Food traditions are carried forward by people. We value the time, skill and care that women contribute to this work, and the knowledge passed from one generation to the next.</p><p>Empowering women is part of the community we want to build.</p><Link className="text-link" href="/stories/women-behind-jain-desi-and-pure">Read our community story →</Link></div></div></section>;}
