import Link from 'next/link';
import {stores} from '../lib/contact';
import {womenWorkforceImage} from '../lib/brandAssets';

export function HomeProcess(){return <section id="process" className="home-process home-section home-visit"><div className="container home-visit-grid"><img src="/images/chakki-banner.jpg" alt="Traditional milling at Jain Desi & Pure" loading="lazy"/><div><span className="eyebrow">See the process firsthand</span><h2>Don't Just Take Our Word for It. Come See.</h2><p>Visit our Sector 122 store in Noida to witness live processing and learn more about the food you bring home.</p><div className="home-visit-details"><div><span className="material-symbols-outlined" aria-hidden="true">location_on</span><strong>Sector 122, Noida</strong><span>Visit our main store</span></div><div><span className="material-symbols-outlined" aria-hidden="true">visibility</span><strong>Live Processing</strong><span>See the process firsthand</span></div></div><p className="home-visit-hours">{stores[0].hours}</p><a className="btn btn-primary" href={stores[0].map} target="_blank" rel="noopener noreferrer">Get Directions →</a></div></div></section>;}

const purpose=[['Our vision','We want every child to grow up with better food.','Not food that is simply convenient. Not food that is unnecessarily processed and contains chemicals. But food made with good ingredients, traditional wisdom, uncompromising care and chemical free.'],['Our mission','Putting Their Health First, Today and for Generations to Come.','To make pure, wholesome everyday food accessible to each and every Indian families, helping parents make better choices today and build healthier food habits for generations to come.'],['Our belief','Purity, Not Packaging.','We believe what goes into your food matters more than how it is presented. Our focus is on the ingredients, the process, and the people who bring that food to the table.']];
export function HomeMission(){return <section id="mission" className="home-purpose home-section"><div className="container"><div className="home-section-heading"><div><span className="eyebrow">Our purpose</span><h2>Why Jain Desi &amp; Pure exists.</h2></div></div><div className="home-purpose-panels">{purpose.map(([label,title,text])=><article key={label}><span className="eyebrow">{label}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>;}

export function HomeWomen(){return <section id="women" className="home-women home-section"><div className="container home-women-grid"><div className="home-women-image"><img src={womenWorkforceImage} alt="An illustration of women working together in food preparation" loading="lazy"/></div><div className="home-women-copy"><span className="eyebrow">Women at the heart of our work</span><h2>Driven By Women.<br/><em>Rooted in care.</em></h2><p>Food traditions are carried forward by people. We value the time, skill and care that women contribute to this work, and the knowledge passed from one generation to the next.</p><p>Empowering women is part of the community we want to build.</p><Link className="text-link" href="/stories/women-behind-jain-desi-and-pure">Read our community story →</Link></div></div></section>;}
